name: G-Homa Control Server
version: 1.0.0
slug: ghoma
description: Controlling G-Homa plugs locally
url: https://github.com/cschmatzler/home-assistant-addons/tree/main/ghoma
image: ghcr.io/cschmatzler/ghoma:1.0.0
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
ports:
  - 4196/tcp:4196
