name: G-Homa Control Server
version: 1.0.1
slug: ghoma
description: Controlling G-Homa plugs locally
url: https://github.com/cschmatzler/home-assistant-addons/tree/main/ghoma
init: true
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
ports:
  4196/tcp: 4196
